### ISSUE TITLE
Sharing common templates across Node modules?

### ISSUE THREAD

**Issue by kristianmandrup** [raptorjs/marko#102]
Hi again,

I've been working on a large Koa server project where we want to allow mounting of multiple SPAs using Marko. Each SPA is a separate Node package (module).
It would be really nice if we could specify the root common templates folder for each page. 

The following should give an idea of my ideal application layout, split into a module for each SPA.
The `app.js` is the main app, which contains shared layout and partials for all SPAs to leverage.

```sh
app.js
: require koa-server.js
  - default-layout.marko
  - partials
    - _header.marko
    - _footer,marko

index.je
: require app.js
  - index.marko
  - index-layout.marko

live.js 
: require app.js
  - live.marko
  - live-layout.marko
```

Alternatively I would have a `common.js` module, with the templates, layouts and partials common (shared) across multiple SPAs.

```sh
common.js
  - partials
    - _header.marko
    - _footer,marko

live.js
: require app.js
: require common.js
  - live.marko
  - live-layout.marko
```

How would I conveniently reference such shared templates locations in other node modules, without hard coding a long ugly path such as `./node_modules/common/partials/_header`?
Would this be a feature enhancement/request?

Any ideas or recommendations greatly appreciated. Thanks ;)

**Comment by patrick-steele-idem** [comment]
Hi @kristianmandrup, you should probably be using custom tags instead of partials. Custom tags are superior to vanilla partials in many ways and are often easier to use.

Instead of the following:

```xml
<include template="../../path/to/header.marko" ... />
```

Just make header a custom tag:

```xml
<my-header .../>
```

With custom tags, the path of the partial template doesn't matter and Marko makes it easy to utilize custom tags provided by installed Node modules. Custom tags can be associated with a JavaScript renderer or just a template (if a JavaScript renderer is not needed).

It is considered a bad practice to use includes/partials where the target partial template is outside the current directory of the parent template. That is, a partial is probably fine if it the parent template and the partial template are in the same directory.
```

If you create a Node.js module that is to export custom tags, just put a `marko-taglib.json` in the root of the module. I recommend taking advantage of directory scanning for automatically discovering taglibs based on the directory structure. Please see [Scanning for Tags](https://github.com/raptorjs/marko#scanning-for-tags).

The marko compiler will automatically discover the exported taglib of installed modules and make the taglib available to any template that has the taglib in its search path. Please see [Taglib Discovery](https://github.com/raptorjs/marko#taglib-discovery)

I hope that answers your question. Please let me know if you would like to discuss some more. I will try to put together a sample project that illustrates creating and utilizing custom tags.

**Comment by kristianmandrup** [comment]
Awesome! Thanks a lot Patrick! Will start switching to Custom Tags for more awesome power and flexibility.

**Comment by patrick-steele-idem** [comment]
Closing issue for now, but please feel free to add additional comments. Thanks.
