### ISSUE TITLE
Rendering in express without the marko.js files being created

### ISSUE THREAD

**Issue by snapwich** [raptorjs/marko#103]
I might be doing something wrong, but whenever my express app hits the `var template = require('./hello.marko');` a `hello.marko.js` file is created alongside the original file.  Is there a way to render marko templates from node without this filesystem dependency?

Thanks.

**Comment by yomed** [comment]
One of the main benefits of Marko is that templates are compiled to javascript so that they can be executed on both client and server. Is there a particular reason that you're trying to avoid compilation?

**Comment by snapwich** [comment]
I don't have any problem with a compilation step, most templating systems behave similarly.  I'm just wondering if it's required to compile to the filesystem as opposed to having a purely in-memory compilation.

**Comment by snapwich** [comment]
Sorry I missed your part about the template-compilation with Javascript API.

I attempted using compileFile but the source that is returned is in the format of a common js module, which still isn't of much use unless it gets written to a file.  I was kind of hoping to somehow get back a compiled template function that can be instantly ran, similar to https://lodash.com/docs#template

**Comment by patrick-steele-idem** [comment]
Hi @snapwich, this question has come up before and here is a relevant discussion: https://github.com/raptorjs/marko/issues/6

The main reason for writing the compiled template to disk is so that stack traces will be valid in case there is an exception thrown during template rendering. By design, the Marko template compiler produces very readable JavaScript output. It would be extremely frustrating to debug a JavaScript exception if the loaded source code was not available.

In addition, the compiled template _must_ be loaded through the Node.js module loader (or a compatible CommonJS module loader of some sort). If you take a close look at the compiled output of a template you will see that most templates make heavy use of the `require` function that is only available inside the context of a CommonJS module. The `require` function is used to load included templates, custom tags, etc. In other words, you can't just `eval` the compiled output and expect things to work.

In theory, we could provide an option to disable the writing of the compiled Marko template to disk with a small code change but I think that would be undesirable. I'm happy to discuss some more and would not necessarily be opposed to a PR (as long as the default was still to write the compiled template to disk).

Let me know if you still have questions. Thanks.

**Comment by snapwich** [comment]
Thanks for the relevant issue, I searched but did not find that somehow.  That answers my question.
