### ISSUE TITLE
Passing data to components

### ISSUE THREAD

**Issue by patbegg** [raptorjs/marko#55]
Hi,
Whats the best way to pass data to components. At present it appears you have to pass data from every template to the components e.g. in index.marko you would have
`<app-header title="$data.title" env="$data.env" csrf="$data.csrf"></app-header>`

I can then access the data from the component e.g.
`<if test="data.env == 'development'">`

If I try to access data.env without passing the data in from index.marko I get an error. Doing it this way if I want to pass new data into the app-header component in the future I would have to change ALL templates. 
Is there a better way of doing this?

Thanks,
Pat (new to Marko and Node)

**Comment by patrick-steele-idem** [comment]
Welcome to Marko and Node, @patbegg! There are two ways to pass along data:

1. As part of the attributes on the custom tag
2. As part of global data that is made available to all custom tags (as part of the `out` object).

You want to take advantage of the second option and provide global data. This is described in the following section of the docs: https://github.com/raptorjs/marko#global-properties

Here's some code that matches your example:

```javascript
template.render({
        $global: {
            env: 'development'
        },
        ... // All other non-global data
    });
```

And then in any rendered template:

```html
<if test="out.global.env == 'development'">
```

NOTE: `out.global.env` is used instead of `data.env`.

Please confirm that that solves your problem. Let us know know if you have any other questions.

**Comment by patbegg** [comment]
Wow, exactly what I needed, and fast! I can get on with a productive day, much appreciated.

**Comment by patrick-steele-idem** [comment]
Glad that solved your problem. Happy coding!
