### ISSUE TITLE
dynamic custom tag names

### ISSUE THREAD

**Issue by yomed** [raptorjs/marko#94]
I would like to determine which custom tags get called via my renderer.js

So in the renderer, something like this:
`data.details=['d1','d2','d3']`

And then in template.marko (which doesn't work):
`<for each="detail in data.details">`
&nbsp;&nbsp;&nbsp;&nbsp;`    <${detail} />`
`</for>`

One solution would be to explicitly call out tags conditionally:
`<for each="detail in data.details">`
&nbsp;&nbsp;&nbsp;&nbsp;`    <if test="detail==='d1'">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`        <d1 />`
&nbsp;&nbsp;&nbsp;&nbsp;`    </if>`
`</for>`

But is there any other way to accomplish this?

**Comment by patrick-steele-idem** [comment]
Hi @yomed, instead of a custom tag (which is associated with a renderer function) you can invoke a `renderer(input, out)` function directly:

```javascript
data.renderers=[
    require('../foo'),
    require('../bar'),
    require('../baz')
]
```

```xml
<for each="renderer in data.renderers">
    <invoke function="renderer(myInputObject, out)"/>
</for>
```

I don't know exactly how that fits into your app, but hopefully you get the idea. FYI, a custom tag is resolved to a renderer at compile-time.

Please let me know if that doesn't solve your problem.

**Comment by yomed** [comment]
Thanks Patrick, that seems to work well. Do you know how I might include w-id in this case?

So that 
```
<detail w-id="detail[]" />
```

would become something like this...
```
<invoke function="renderer(data, out)" w-id="detail[]" />
```

**Comment by patrick-steele-idem** [comment]
Assigning a `w-id` attribute to an `<invoke>` tag currently doesn't work because of how the compile-time transform is implemented for marko-widgets. I'll look into seeing if it can be supported with a small code change. Can you please open a Github issue against the [marko-widgets](https://github.com/raptorjs/marko-widgets) project?

**Comment by yomed** [comment]
Ok thanks. That would be great if this could be supported.

**Comment by patrick-steele-idem** [comment]
marko-widgets was updated to support the `w-id` attribute with the `<invoke>` tag: https://github.com/raptorjs/marko-widgets/issues/46

Closing this issue.
